# Load the human_review_queue file for manual revision

In [175]:
#load the csv file evaluation_v2\run_20260809_170051\human_review_queue_reviwed.xlsx into a pandas dataframe and print the first 5 rows
import pandas as pd
from pathlib import Path

ROOT = Path.cwd().resolve().parent.parent

review_path = (
    ROOT
    / "evaluation_v2"
    / "run_20260809_170051"
    / "human_review_queue.csv"
)

df = pd.read_csv(
    review_path,
    dtype={
        "human_covered_claims": "string",
        "human_decision": "string",
        "human_notes": "string",
        "adjudicator": "string",
        "adjudication_notes": "string",
    },
    keep_default_na=False,
)

df["human_grade"] = pd.to_numeric(
    df["human_grade"],
    errors="coerce"
).astype("Int64")

In [176]:
# mostrar el texto completo de todas las columnas del dataframe
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# Review each row one by one

In [356]:
#print row 1 
df.iloc[[145]]

,review_id,question_id,claim_id,evidence_id,question,claim_text,evidence_text,doc_id,page_num,machine_grade,machine_confidence,issue_type,review_question,machine_rationale,human_grade,human_covered_claims,human_decision,human_notes,adjudicator,adjudicated_grade,adjudication_notes
145,R00146,Q028,Q028-C01,Q028-E0028,¿Cuáles son las mutaciones genéticas más frecuentes en cáncer de mama y ovario hereditario?,Mutations in BRCA1 and BRCA2 high penetrance genes account for most hereditary breast and ovarian cancer.,"nically meaningful benefit in radiological PFS in men with BRCA1, BRCA2, or ATM mutations in metastatic castration-resistant prostate cancer, and in PFS as maintenance therapy in pancreatic cancer following platinum-based chemotherapy regimen. Nonetheless, indications for each agent will continue to evolve in keeping with upcoming and ongoing clinical trials. Management of women with familial risk and no germline mutation For those women with a positive family history of BC and no mutation in a high/moderate penetrance gene, BC risk can be estimated by predictive models, such as BOADICEA or Tyrer-Cuzyck.",mama_en_seom-geicam-solti_clinical-guidelines-hereditary-breast-ovarian-cancer_2019,6,2,medium,machine_evidence_judgment_review,"Confirm claim segmentation, evidence grade, scope and direct support.",substantial but incomplete direct token coverage; best_token_coverage=0.7273; text_verified_in=DB_snapshot,2,,uncertain,La evidencia es inconclusa. Hace falta revisarla,,,

In [596]:
row = 0

df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q002-C01; Q002-C03"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia respalda directamente y de forma completa el claim Q002-C01."
)

In [597]:
row = 1
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q002-C01; Q002-C02; Q002-C03"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia respalda el claim de manera completa"
)

In [598]:
row = 2
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q002-C03; Q002-C04"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia respalda el claim de manera completa"
)

In [599]:
row = 3
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q002-C05; Q002-C03"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia respalda el claim de manera completa"
)

In [600]:
row = 4
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q005-C01"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia respalda el claim de manera completa"
)

In [601]:
row = 5
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q006-C01"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia respalda el claim de manera completa"
)

In [602]:
row = 6
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q008-C01; Q008-C02"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia respalda el claim de manera completa"
)

In [603]:
row = 7
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q008-C01; Q008-C02"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia respalda el claim de manera completa"
)

In [604]:
row = 8
df.at[row, "human_grade"] = 0
#df.at[row, "human_covered_claims"] = 
df.at[row, "human_decision"] = "reject"

In [605]:
row = 9
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [606]:
row = 10
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = "rewrite to: Los principales efectos secundarios son: Anorexia, Artralgia, Caídas, Diarrea, Disminución de peso, Fatiga, Fracturas, Hipertensión, Sarpullido, Sofocos."

In [607]:
row = 11
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q012-C01"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia apoya el claim."
)

In [608]:
row = 12
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no respalda el claim. La combinación de radioterapia y TPA se presenta en el diagrama para cáncer de próstata localizado de riesgo intermedio, no para enfermedad localmente avanzada. El texto que menciona enfermedad localmente avanzada no confirma esa combinación terapéutica. Evidencia de ámbito clínico incorrecto."
)

In [609]:
row = 13
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no respalda el claim: no menciona recidiva tras prostatectomía ni radioterapia en la zona prostática. Además, el claim no responde directamente a la pregunta, que solicita tipos de cáncer tratados con terapia de privación de andrógenos. Marcar el claim para revisión de relevancia o retirada."
)

In [610]:
row = 14
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = (
    "La evidencia no respalda el claim"
)

In [611]:
row = 15
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no respalda el claim. Además la evidencia proviene de información sobre el cancer de mama y la pregunta es sobre cáncer de próstata"
)

In [612]:
row = 16
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no respalda el claim. Además la evidencia proviene de información sobre el cancer de mama y la pregunta es sobre cáncer de próstata"
)

In [613]:
row = 17
df.at[row, "human_grade"] = 2
df.at[row, "human_covered_claims"] = "Q013-C11"
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = (
    "La evidencia soporta parcialmente el claim ya que el claim no especifica tipo de cancer (mama, próstata, etc.) mientras que la evidencia sí"
)

In [614]:
row = 18
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no soporta el claim"
)

In [615]:
row = 19
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q013-C11"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia soporta el claim"
)

In [616]:
row = 20
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q014-C02"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia soporta el claim"
)

In [617]:
row = 21
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q014-C02"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia soporta el claim"
)

In [618]:
row = 22
df.at[row, "human_grade"] = 1
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia es relacionada con la función sexual tras cirugía, pero no informa sobre la eyaculación. El claim “Problemas de erección” no responde directamente a la pregunta y debe revisarse o retirarse como claim requerido."
)

In [619]:
row = 23
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim. El claim “Problemas de erección” no responde directamente a la pregunta y debe revisarse o retirarse como claim requerido."
)

In [620]:
row = 24
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim. Además la pregunta solicita información sobre cáncer de próstata, mientras que la evidencia se refiere a cáncer de mama."
)

In [621]:
row = 25
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim. Además la pregunta solicita información sobre cáncer de próstata, mientras que la evidencia se refiere a cáncer de mama."
)

In [622]:
row = 26
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [623]:
row = 27
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [624]:
row = 28
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [625]:
row = 29
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [626]:
row = 30
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [627]:
row = 31
df.at[row, "human_grade"] = 1
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim de manera directa. Menciona efectos secundarios pero no directamente la fertilidad."
)

In [766]:
row = 32
df.at[row, "human_grade"] = 3
df.at[row, "human_decision"] = "accept"
df.at[row, "human_covered_claims"] = "Q015-C10; Q015-C01"
df.at[row, "human_notes"] = (
    "La evidencia apoya este claim."
)

In [629]:
row = 33
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [630]:
row = 34
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [631]:
row = 35
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [632]:
row = 36
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [633]:
row = 37
df.at[row, "human_grade"] = 3
df.at[row, "human_decision"] = "accept"
df.at[row, "human_covered_claims"] = "Q016-C04"
df.at[row, "human_notes"] = (
    "La evidencia apoya este claim."
)

In [634]:
row = 38
df.at[row, "human_grade"] = 3
df.at[row, "human_decision"] = "accept"
df.at[row, "human_covered_claims"] = "Q016-C04"
df.at[row, "human_notes"] = (
    "La evidencia apoya este claim."
)

In [635]:
row = 39
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [636]:
row = 40
df.at[row, "human_grade"] = 3
df.at[row, "human_decision"] = "accept"
df.at[row, "human_covered_claims"] = "Q016-C05"
df.at[row, "human_notes"] = (
    "La evidencia apoya este claim."
)

In [637]:
row = 41
df.at[row, "human_grade"] = 3
df.at[row, "human_decision"] = "accept"
df.at[row, "human_covered_claims"] = "Q016-C05"
df.at[row, "human_notes"] = (
    "La evidencia apoya este claim."
)

In [638]:
row = 42
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [639]:
row = 43
df.at[row, "human_grade"] = 3
df.at[row, "human_decision"] = "accept"
df.at[row, "human_covered_claims"] = "Q016-C06"
df.at[row, "human_notes"] = (
    "La evidencia apoya este claim."
)

In [640]:
row = 44
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [641]:
row = 45
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = "rewrite to: Several studies have shown the prognostic value of ROR score in estimating risk of disease recurrence."

In [642]:
row = 46
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [643]:
row = 47
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [644]:
row = 48
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [645]:
row = 49
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [646]:
row = 50
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [647]:
row = 51
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [648]:
row = 52
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [649]:
row = 53
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [650]:
row = 54
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = "rewrite to: Several studies have shown the prognostic value of ROR score in estimating risk of disease recurrence"

In [651]:
row = 55
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [652]:
row = 56
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [653]:
row = 57
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [654]:
row = 58
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [655]:
row = 59
df.at[row, "human_grade"] = 3
df.at[row, "human_decision"] = "accept"
df.at[row, "human_covered_claims"] = "Q018-C05"
df.at[row, "human_notes"] = (
    "La evidencia apoya este claim."
)

In [656]:
row = 60
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [657]:
row = 61
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [658]:
row = 62
df.at[row, "human_grade"] = 3
df.at[row, "human_decision"] = "accept"
df.at[row, "human_covered_claims"] = "Q019-C01"
df.at[row, "human_notes"] = (
    "La evidencia apoya este claim."
)

In [659]:
row = 63
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [660]:
row = 64
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [661]:
row = 65
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [662]:
row = 66
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [663]:
row = 67
df.at[row, "human_grade"] = 2
df.at[row, "human_covered_claims"] = "Q019-C04"
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = (
    "La evidencia apoya el claim pero no queda claro si responde del todo a la pregunta. Ya que la evidencia habla de terapias endocrinas en general y la pregunta es sobre los efectos secundarios del tamoxifeno"
)

In [664]:
row = 68
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim. La evidencia habla sobre otro tipo de terapias para el cancer de mama, no del tamoxifeno"
)

In [665]:
row = 69
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim. La evidencia habla sobre otro tipo de terapias para el cancer de mama, no del tamoxifeno"
)

In [666]:
row = 70
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim. La evidencia habla sobre otro tipo de terapias para el cancer de mama, no del tamoxifeno"
)

In [667]:
row = 71
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q019-C04"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [668]:
row = 72
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("rewrite to: Algunos efectos secundarios son: Aumento de la sudoración, Complicaciones tromboembólicas, Engrosamiento endometrial, Fatiga, Náuseas, Retención de líquidos, Sangrado/secreción vaginal, Sarpullido cutáneo, Sofocos y Trastornos visuales")

In [669]:
row = 73
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [670]:
row = 74
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = "reject. El claim está incompleto. "

In [671]:
row = 75
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [672]:
row = 76
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [673]:
row = 77
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [674]:
row = 78
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [675]:
row = 79
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [676]:
row = 80
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [677]:
row = 81
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [678]:
row = 82
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [679]:
row = 83
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q020-C10"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [680]:
row = 84
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [681]:
row = 85
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q020-C11"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [682]:
row = 86
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [683]:
row = 87
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [684]:
row = 88
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [685]:
row = 89
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q020-C14"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [686]:
row = 90
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q020-C14"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [687]:
row = 91
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q020-C14"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [688]:
row = 92
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q020-C14"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [689]:
row = 93
df.at[row, "human_grade"] = 1
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "Aunque parece que la evidencia resplada el claim, la evidencia habla sobre cáncer de próstata y el tamoxifeno es un tratamiento para cáncer de mama."
)

In [690]:
row = 94
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [691]:
row = 95
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [692]:
row = 96
df.at[row, "human_grade"] = 1
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "Aunque la evidencia menciona los síntomas del claim, no se refieren a lo mismo."
)

In [693]:
row = 97
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = "El claim aparece textualmente en mama_es_novartis_guia-pacientes-CM_2025.pdf"

In [694]:
row = 98
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q021-C07"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [695]:
row = 99
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q023-C01"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [696]:
row = 100
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q023-C02"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [697]:
row = 101
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q025-C01"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [698]:
row = 102
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q025-C06"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [699]:
row = 103
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q025-C08"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [700]:
row = 104
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [701]:
row = 105
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = "rewrite to: Existen varios factores de riesgo asociados al cáncer de mama, que pueden dividirse en factores de riesgo modificables o no modificables."

In [702]:
row = 106
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = "rewrite to: La mayor parte de los factores de riesgo se relaciona con los antecedentes reproductivos que modulan la exposición hormonal durante la vida."

In [703]:
row = 107
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [704]:
row = 108
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [705]:
row = 109
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no apoya este claim."
)

In [706]:
row = 110
df.at[row, "human_grade"] = 1
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia menciona el mayor riesgo con la edad pero se refieren a cosas diferentes. El claim habla de los factores de riesgo para el cáncer de mama y la evidencia sobre la quimioterapia."
)

In [707]:
row = 111
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia habla sobre cancér de próstata y el claim sobre cáncer de mama. No hay relación entre ambos.")

In [708]:
row = 112
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia habla sobre cancér de próstata y el claim sobre cáncer de mama. No hay relación entre ambos.")

In [709]:
row = 113
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = "rewrite to: La historia personal puede ser un factor de riesgo para padecer cáncer de mama. Por ejemplo, las mujeres que han tenido un cáncer de mama invasivo tienen más riesgo de padecer un cáncer de mama contralateral."

In [710]:
row = 114
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [711]:
row = 115
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [712]:
row = 116
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [713]:
row = 117
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [714]:
row = 118
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = "reject"

In [715]:
row = 119
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [716]:
row = 120
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [717]:
row = 121
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = ("rewrite to: El consumo de alcohol es un factor de riesgo para el cáncer de mama.")

In [718]:
row = 122
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [719]:
row = 123
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = ("rewrite to: El sedentarismo es un factor de riesgo para el cáncer de mama.")

In [720]:
row = 124
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [721]:
row = 125
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [722]:
row = 126
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [723]:
row = 127
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [724]:
row = 128
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = ("rewrite to: El género femenino es un factor de riesgo para el cáncer de mama.")

In [725]:
row = 129
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = ("rewrite to: La edad avanzada es un factor de riesgo para el cáncer de mama.")

In [726]:
row = 130
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "El claim habla sobre un factor de riesgo del cáncer de mama y la evidencia sobre la teleasistencia.")

In [727]:
row = 131
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [728]:
row = 132
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [729]:
row = 133
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [730]:
row = 134
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [731]:
row = 135
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [732]:
row = 136
df.at[row, "human_decision"] = "accept"

In [733]:
row = 137
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = ("rewrite to: La obesidad es un factor de riesgo para el cáncer de mama.")

In [734]:
row = 138
df.at[row, "human_decision"] = "accept"

In [735]:
row = 139
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = ("rewrite to: El alcohol es un factor de riesgo para el cáncer de mama.")

In [736]:
row = 140
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [737]:
row = 141
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [738]:
row = 142
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = ("reject. El claim no responde a la pregunta")

In [739]:
row = 143
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no soporta el claim.")

In [740]:
row = 144
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [741]:
row = 145
df.at[row, "human_grade"] = 2
df.at[row, "human_covered_claims"] = "Q028-C01"
df.at[row, "human_decision"] = "uncertain"
df.at[row, "human_notes"] = (
    "La evidencia es inconclusa. Hace falta revisarla")

In [742]:
row = 146
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no soporta el claim.")

In [743]:
row = 147
df.at[row, "human_grade"] = 0
df.at[row, "human_decision"] = "reject"
df.at[row, "human_notes"] = (
    "La evidencia no soporta el claim. La evidencia habla sobre cáncer de próstata y el claim sobre cáncer de mama. No hay relación entre ambos.")

In [744]:
row = 148
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [745]:
row = 149
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [746]:
row = 150
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [747]:
row = 151
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q028-C04"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [748]:
row = 152
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q028-C04"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia si apoya el claim."
)

In [749]:
row = 153
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [750]:
row = 154
df.at[row, "human_grade"] = 2
df.at[row, "human_covered_claims"] = "Q028-C05"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "Soporta el claim de manera parcial."
)

In [751]:
row = 155
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [752]:
row = 156
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [753]:
row = 157
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [754]:
row = 158
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [755]:
row = 159
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [756]:
row = 160
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q028-C10"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia soporta el claim."
)

In [757]:
row = 161
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q028-C10"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia soporta el claim."
)

In [758]:
row = 162
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = ("keep")

In [759]:
row = 163
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q028-C11"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia soporta el claim."
)

In [760]:
row = 164
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q030-C03"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia soporta el claim."
)

In [761]:
row = 165
df.at[row, "human_grade"] = 3
df.at[row, "human_covered_claims"] = "Q031-C02"
df.at[row, "human_decision"] = "accept"
df.at[row, "human_notes"] = (
    "La evidencia soporta el claim."
)

In [765]:
df.iloc[[165]]

#mostrar las filas que tienen en la columna issue_type el valor "claim_segmentation_review"

df[df["claim_id"] == "Q015-C10"]

,review_id,question_id,claim_id,evidence_id,question,claim_text,evidence_text,doc_id,page_num,machine_grade,machine_confidence,issue_type,review_question,machine_rationale,human_grade,human_covered_claims,human_decision,human_notes,adjudicator,adjudicated_grade,adjudication_notes
32,R00033,Q015,Q015-C10,Q015-E0086,¿Cómo afecta la prostatectomía radical a la eyaculación?,"Las complicaciones más frecuentes de este tipo de cirugía son la incontinencia urinaria y la disfunción eréctil, que suelen aparecer inmediatamente después de la cirugía con opción de mejorar con el paso del tiempo (unos 12 y 18 meses, respectivamente).","Las complicaciones más frecuentes de este tipo de cirugía son la incontinencia urinaria y la disfunción eréctil, que suelen aparecer inmediatamente después de la cirugía con opción de mejorar con el paso del tiempo (unos 12 y 18 meses, respectivamente).",prostata_es_seom_cancer-prostata_2025,11,3,high,machine_evidence_judgment_review,"Confirm claim segmentation, evidence grade, scope and direct support.",claim text appears directly in evidence; best_token_coverage=1.0000; text_verified_in=PDF,3,"Q015-C10, Q015-C01",accept,La evidencia apoya este claim.,,,

# Save dataframe reviewed

In [767]:
#Save the dataframe to a new csv file
output_path = (
    ROOT
    / "evaluation_v2"
    / "run_20260809_170051"
    / "human_review_queue_reviewed.csv"
)

df.to_csv(output_path, index=False)

In [764]:
#load again the file to check that it was saved correctly
df_check = pd.read_csv(
    output_path,
    dtype={
        "human_covered_claims": "string",
        "human_decision": "string",
        "human_notes": "string",
        "adjudicator": "string",
        "adjudication_notes": "string",
    },
    keep_default_na=False,
)